sudo: false
language: c++

notifications:
  email:
    on_success: change
    on_failure: always
git:
  depth: 5

env:
  global:
    - CMAKE_OPTIONS_GLOBAL="-DCMAKE_EXPORT_COMPILE_COMMANDS=ON"
    # COVERALLS_REPO_TOKEN added as env var in travis project
    - COVERALLS_SERVICE_NAME=travis-ci

compiler:
  - clang
  - gcc
os: linux

addons:
  apt:
    packages: ["lcov", "curl"]
  coverity_scan:
    # COVERITY_SCAN_TOKEN added as env var in travis project
    project:
      name: iboB/mathgp
    notification_email: b.stanimirov@abv.bg
    build_command_prepend: cd test/unit_test && cmake .
    build_command: make

script:
  # initial run with options
  - cd test/unit_test
  - cmake ${CMAKE_OPTIONS_GLOBAL} . -DCMAKE_BUILD_TYPE=Debug
  - make -j2
  - make coveralls
  - ctest --output-on-failure

after_script:
  - cat compile_commands.json
